### DISCUSSION TITLE
Shortcuts to player folders or network shares

### DISCUSSION THREAD

**Discussion by wizmo2** [wizmo2/zidoo-player#13] [General]
After messing around looking at configurable options in the integration it'self, I recently realized that you can create `navigate' paths to jump directly to a specific media browse folder.

1. Use a web browser to access the desired folder in Media.  
2. Copy the url text from '/media-browser/' on.
3. Add a new button to lovelace (use any entity_id)
4. set the Tap action to  'navigate' and paste the url text in the Navigation Path.

For example, adding buttons to the footer of an entities card

```
footer:
  type: buttons
  entities:
    - entity: device_tracker.zidoo
      name: Downloads
      icon: mdi:state-machine
      tap_action:
        action: navigate
        navigation_path: >-
          /media-browser/media_player.<player_name>/url%2C%2Ftmp%2Framfs%2Fmnt%2F/file%2C%252Ftmp%252Framfs%252Fmnt%252F<ipaddress>%2523<path>
```
