### DISCUSSION TITLE
beta-260124

### DISCUSSION THREAD

**Discussion by wizmo2** [wizmo2/zidoo-player#23] [Announcements]
Update Zidoo API to `asyncio`, plus general cleanup and fixes aimed at improving responsiveness and and overall functionality.  Also included is a separate virtual Remote Entity, which proves a more standard interface for sending key commands.

**NOTE:  This release includes embedded Rapid Update.  If you are currently using an automation based on the documentation example, this can now be removed, but please re-enable automatic update if necessary**

Please give it a try and report any issues.

## Changes
1. replace `zidoorc` with aync version `zidooapi` 
2. Update integration to support new functions (#20 fix blocking call "bug").
3. Add Rapid update when player is on
4. Major cleanup and optimization of code.
5. Add Remote Entity support (#22 thanks @albaintor) _NOTE:  This will eventually replace the 'Send Key' service
6. Fix progress time units from ms to seconds.
7. Improve browsing and search functions with Media Browser

<hr /><em>This discussion was created from the release <a href='https://github.com/wizmo2/zidoo-player/releases/tag/beta-260124'>beta-260124</a>.</em>

**Comment by albaintor** [comment]
Hi, thank you for your hard work.
I am currently testing the new release and it is working well so far.
I have tried to configure the AndroidTV remote entity card which is highly customizable :
<img width="294" alt="image" src="https://github.com/wizmo2/zidoo-player/assets/118518828/823d9511-cfa3-40d3-ba9b-72a6154a9c48">

With the following yaml :
```yamll
type: custom:android-tv-card
remote_id: remote.z20_pro
slider_id: media_player.z20_pro
title: Zidoo
rows:
  - - power
    - channel_up
    - info
    - channel_down
  - - vol_buttons
  - - dpad
  - - back
    - home
    - tv
  - - rewind
    - play
    - pause
    - fast_forward
custom_actions:
  power:
    icon: mdi:power
    tap_action:
      action: key
      key: Key.PowerOn
    hold_action:
      action: key
      key: Key.PowerOn.Reboot
  menu:
    icon: mdi:menu
    tap_action:
      action: key
      key: Key.Menu
  home:
    tap_action:
      action: key
      key: Key.Home
    hold_action:
      action: key
      key: Key.PopMenu
  back:
    tap_action:
      action: key
      key: Key.Back
  channel_up:
    tap_action:
      action: key
      key: Key.PageUP
  channel_down:
    tap_action:
      action: key
      key: Key.PageDown
  skip-backward:
    icon: mdi:rewind-10
    tap_action:
      action: key
      key: Key.MediaBackward
  skip-forward:
    icon: mdi:fast-forward-10
    action: key
    key: Key.MediaForward
  play:
    tap_action:
      action: key
      key: Key.MediaPlay
  pause:
    tap_action:
      action: key
      key: Key.MediaPause
  up:
    tap_action:
      action: key
      key: Key.Up
  down:
    tap_action:
      action: key
      key: Key.Down
  left:
    tap_action:
      action: key
      key: Key.Left
  right:
    tap_action:
      action: key
      key: Key.Right
  center:
    tap_action:
      action: key
      key: Key.Select
  tv:
    tap_action:
      action: key
      key: Key.movie
  info:
    tap_action:
      action: key
      key: Key.PopMenu
```
