### DISCUSSION TITLE
How to change the source for audio input and audio output on the UHD8000

### DISCUSSION THREAD

**Discussion by from777** [wizmo2/zidoo-player#35] [General]
With this integration is it possible to set which output and input I need ?

I asked zidoo support for the commands and they look like this, the ip address needs to be changed to my address

Input source switching
http://192.168.11.200:9529/ZidooMusicControl/v2/setInputList?tag=XMOS&index=0
http://192.168.11.200:9529/ZidooMusicControl/v2/setInputList?tag=USB&index=1

Output switching:
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=XLR&index=0
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=RCA&index=1
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=XLRRCA&index=2
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=HDMI&index=3
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=HDMI2&index=4
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=SPDIF&index=5
http://192.168.11.200:9529/ZidooMusicControl/v2/setOutInputList?tag=USB&index=6

**Comment by wizmo2** [comment]
Dont have access to a UHD8000, but I'll have a look at it.  May need your help testing   if that is OK

**Comment by from777** [comment]
> Dont have access to a UHD8000, but I'll have a look at it. May need your help testing if that is OK

I will be happy to help in testing, also I have a problem with the display of cameras on rstp and onvif here is more detailed https://community.home-assistant.io/t/does-not-show-cctv-cameras-on-zidoo-via-home-assistan/789889 if it is also somehow related to the model of the player is also ready to test everything.

**Comment by wizmo2** [comment]
> ... also I have a problem with the display of cameras on rstp and onvif here is more detailed https://community.home-assistant.io/t/does-not-show-cctv-cameras-on-zidoo-via-home-assistan/789889 if it is also somehow related to the model of the player is also ready to test everything.

This may be a limitation of the zidoo codecs and rtsp.  I haven't found a reliable method of displaying camera feeds as yet.  The only success I've had is to use something like Jellyfin to re-encode to HLS.  I did see a write up of doing something similar within HA [streams](https://www.home-assistant.io/integrations/stream/).  You could try expermenting.

**Comment by from777** [comment]
> This may be a limitation of the zidoo codecs and rtsp. I haven't found a reliable method of displaying camera feeds as yet. The only success I've had is to use something like Jellyfin to re-encode to HLS. I did see a write up of doing something similar within HA [streams](https://www.home-assistant.io/integrations/stream/). You could try expermenting.

If you can find a link to the article it would be appreciated. And what about onvif ?

**Comment by wizmo2** [comment]
> If you can find a link to the article it would be appreciated. And what about onvif ?

https://community.home-assistant.io/t/i-tried-all-the-camera-platforms-so-you-dont-have-to/222999?page=12
https://www.home-assistant.io/integrations/stream/

If you make any headway, let us know

**Comment by wizmo2** [comment]
I had a quick look at this, and am thinking that it is beyond the scope of this integration.

The calls seem to be similar to the existing `SystemSettings/audio` controls.  I have tried to avoid adding System Settings as the status would have to be independently monitored, and there is more potential to brick/corrupt the system.  

Typically I recommend using the remote 'Send Button Key' service/action for this type of control.  If the supplied remote has additional audio input/output buttons available, perhaps you could go back to the developers and ask if there are custom key commands for them.

**Comment by wizmo2** [comment]
v2.1.0rc2 (theoretically) has code to monitor and select audio output channels [courtousy of @smoothquark).  Do need someone to test as I don't have the harware.

**Reply by Nojeee** [reply]
I came across this while searching for a way to change the audio output channel for my Zidoo UHD8000 via HA. I'd be happy to test as it would be a perfect way to automate the switch between music and video setups.

**Reply by wizmo2** [reply]
> I came across this while searching for a way to change the audio output channel for my Zidoo UHD8000 via HA. I'd be happy to test as it would be a perfect way to automate the switch between music and video setups.

You can download the latest beta version from HACS.  If you have not already added the unit to HA, see the configuration instructions.

Creating an automation should be straight forwards by using a `media_player.select_sound_mode` action based on the `media_content_type` state. 
<img width="303" height="335" alt="image" src="https://github.com/user-attachments/assets/60024369-08da-4969-8121-e7ed7a837af2" />

**Reply by smoothquark** [reply]
Hi. I have done something similar with my Zidoo Z3000. So far, I have the four following YAML scripts (change your entity accordingly). My main HDMI port is connected to my Sony Bravia and then by eARC to my Denon AVC-6500H, whilst the HDMI audio port is connected directly to the Denon. To complicate things, my two channel music via my Lyngdorf (the Denon front LR go to the Lyngdorf too).

I also have a script which changes ports according to whether music or videos are playing (I have disabled it at the moment as I plan to test out switching to USB for 2 channel music to my Lyngdorf). It has been working fine otherwise. I have attached it below the four.

I haven't quite decided whether I want to use all three ports (HDMI main, HDMI audio and USB) or whether to stick to just the HDMI audio and USB ports. The trouble is that I can't quite get the audio delay correct in the Zidoo on the HDMI audio port when watching movies. I think it may be due to my rather ageing Denon - I don't think it is reading the EDIDs correctly (that's another story).

```yaml
alias: Zidoo Audio Output - Denon AVC-6500H change source
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.z3000_pro
    attribute: sound_mode
conditions: []
actions:
  - action: media_player.select_source
    metadata: {}
    data:
      source: >
        {%- if state_attr('media_player.z3000_pro', 'sound_mode') == "HDMI main port" -%}
          Denon AVC-X6500H - TV Audio
        {%- elif state_attr('media_player.z3000_pro', 'sound_mode') == "HDMI audio port" -%}
          Denon AVC-X6500H - Z3000 PRO
        {% endif %}
    target:
      entity_id: media_player.denon_avc_x6500h
mode: single

alias: "Zidoo Audio Output - Lyngdorf TDAI-3400 change source "
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.z3000_pro
    attribute: sound_mode
conditions: []
actions:
  - action: media_player.select_source
    metadata: {}
    data:
      source: >
        {%- if state_attr('media_player.z3000_pro', 'sound_mode') == "USB audio output" -%}
          USB
        {%- else -%}
          Denon AVC-6500H
        {% endif %}
    target:
      entity_id: media_player.lyngdorf_tdai_3400_telnet
mode: single

alias: Zidoo Music Player Playing
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.z3000_pro
    attribute: source
    to:
      - Music Player
conditions: []
actions:
  - action: media_player.select_sound_mode
    metadata: {}
    data:
      sound_mode: HDMI audio port
    target:
      entity_id: media_player.z3000_pro
mode: single

alias: Zidoo Music Player Stopped
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.z3000_pro
    attribute: source
    from:
      - Music Player
    for:
      hours: 0
      minutes: 0
      seconds: 5
conditions: []
actions:
  - action: media_player.select_sound_mode
    metadata: {}
    data:
      sound_mode: HDMI main port
    target:
      entity_id: media_player.z3000_pro
mode: single

alias: Zidoo App Audio Output
description: ""
triggers:
  - trigger: state
    entity_id:
      - media_player.z3000_pro
    attribute: source
conditions: []
actions:
  - action: media_player.select_sound_mode
    metadata: {}
    data:
      sound_mode: >
        {%- if state_attr('media_player.z3000_pro', 'source') == "Video Player" -%}
          HDMI main port
        {%- elif state_attr('media_player.z3000_pro', 'source') == "Music Player" -%}
          HDMI audio port
        {%- else -%}
          HDMI main port
        {% endif %}
    target:
      entity_id: media_player.z3000_pro
mode: single
```

edited:  by @wizmo2 to add [quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) formatting
