### ISSUE TITLE
can you give me you lovercad config, thx!

### ISSUE THREAD

**Issue by kylinfedora** [wizmo2/zidoo-player#1]
can you give me you lovercad config, thx!

**Comment by wizmo2** [comment]
```
media_player:
  - platform: zidoo
    name: Zidoo
    host: 192.168.1.11
```
This is my  home-assistant configuration.  lovelace is a standard mediaplayer card
